### ISSUE TITLE
problem with adding  code in AndroidManifest.xml 

### ISSUE THREAD

**Issue by Sahil-pixel** [SonofPoseidon1982/Py_1982#1]
how to add 
#####
<activity
     android:name="com.unity3d.services.ads.adunit.AdUnitActivity"
     android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"
     android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
     android:hardwareAccelerated="true" />

  <activity
     android:name="com.unity3d.services.ads.adunit.AdUnitTransparentActivity"
     android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"
     android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"
     android:hardwareAccelerated="true" />

  <activity
     android:name="com.unity3d.services.ads.adunit.AdUnitTransparentSoftwareActivity"
     android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"
     android:theme="@android:style/Theme.Translucent.NoTitleBar.Fullscreen"
     android:hardwareAccelerated="false" />

  <activity
     android:name="com.unity3d.services.ads.adunit.AdUnitSoftwareActivity"
     android:configChanges="fontScale|keyboard|keyboardHidden|locale|mnc|mcc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|uiMode|touchscreen"
     android:theme="@android:style/Theme.NoTitleBar.Fullscreen"
     android:hardwareAccelerated="false" />

##
code AndroidManifest.xml via buildozer ?

**Comment by Sahil-pixel** [comment]
okk solved .interstitial ad is working with kivy android.please ad banner ads

**Comment by Sahil-pixel** [comment]
#interstitial ads is showing properly but see log  ..
.
 :  Traceback (most recent call last):
04-09 14:07:17.708 32497 32497 I python  :    File "jnius/jnius_proxy.pxi", line 50, in jnius.jnius.PythonJavaClass.invoke
04-09 14:07:17.709 32497 32497 I python  :    File "jnius/jnius_proxy.pxi", line 76, in jnius.jnius.PythonJavaClass._invoke
04-09 14:07:17.713 32497 32497 I python  :    File "/home/sahil/app_test/.buildozer/android/app/kivunity.py", line 95, in onUnityAdsStart
04-09 14:07:17.714 32497 32497 I python  :  TypeError: 'UnityAdsListener' object is not callable
